export enum AnalyticsUserInfo {
  COUNTRY = 'pais',
  EMAIL = 'correo',
  GENDER = 'genero',
  NETWORK = 'network',
  OPERATING_SYSTEM = 'sistemaoperativo',
  OS_VERSION = 'osversion',
  PLATFORM = 'platform',
  USER_LAST_NAME = 'apellidos usuario',
  USER_NAME = 'nombres usuario',
}

export enum BaseAnalyticsEvents {
  LOGIN_ACTIVAR_RECORDAR_CONTRASEÑA = 'LOGIN_ACTIVAR_RECORDAR_CONTRASEÑA',
  LOGIN_CLIC_INGRESAR = 'LOGIN_CLIC_INGRESAR',
  LOGIN_DESACTIVAR_RECORDAR_CONTRASEÑA = 'LOGIN_DESACTIVAR_RECORDAR_CONTRASEÑA',
  LOGIN_ERROR_LOGUEO_DATOS = 'LOGIN_ERROR_LOGUEO_DATOS',
  LOGIN_ERROR_LOGUEO_SIN_CUENTA = 'LOGIN_ERROR_LOGUEO_SIN_CUENTA',
  LOGIN_INGRESO_CONTRASEÑA = 'LOGIN_INGRESO_CONTRASEÑA',
  LOGIN_LOGUEO_EXITOSO = 'LOGIN_LOGUEO_EXITOSO',
  LOGIN_OLVIDO_CONTRASEÑA = 'LOGIN_OLVIDO_CONTRASEÑA',
  LOGIN_OLVIDO_CONTRASEÑA_CORREO_CLIC = 'LOGIN_OLVIDO_CONTRASEÑA_CORREO_CLIC',
  LOGIN_OLVIDO_CONTRASEÑA_CORREO_RECIBIDO = 'LOGIN_OLVIDO_CONTRASEÑA_CORREO_RECIBIDO',
  LOGIN_OLVIDO_CONTRASEÑA_DIGITA_CORREO = 'LOGIN_OLVIDO_CONTRASEÑA_DIGITA_CORREO',
  LOGIN_OLVIDO_CONTRASEÑA_ENVIAR_CORREO = 'LOGIN_OLVIDO_CONTRASEÑA_ENVIAR_CORREO',
  LOGIN_OLVIDO_CONTRASEÑA_ERROR_CORREO = 'LOGIN_OLVIDO_CONTRASEÑA_ERROR_CORREO',
  LOGIN_OLVIDO_CONTRASEÑA_INGRESAR_NUEVA = 'LOGIN_OLVIDO_CONTRASEÑA_INGRESAR_NUEVA',
  LOGIN_OLVIDO_CONTRASEÑA_OK = 'LOGIN_OLVIDO_CONTRASEÑA_OK',
  LOGIN_OLVIDO_CONTRASEÑA_REENVIAR_CORREO = 'LOGIN_OLVIDO_CONTRASEÑA_REENVIAR_CORREO',
  LOGIN_OLVIDO_CONTRASEÑA_REPETIR_NUEVA = 'LOGIN_OLVIDO_CONTRASEÑA_REPETIR_NUEVA',
}

export type AnalyticsEvents = BaseAnalyticsEvents
